# Generate secret key and copy to clipboard
# :redir @* | !openssl rand -base64 32 | tr -d '\n' | xclip -selection clipboard

[default]
ident      = "questions_api-base"
port       = 8000
address    = "0.0.0.0"
origin_url = "http://localhost:8000"
secret_key = ""

profile_url   = "http://localhost:8001/api/v1/profile/"
user_url      = "http://localhost:8002/api/v1/user/"
auth_url      = "http://localhost:8003/auth/"

message_url   = "http://localhost:8005/api/v1/messaging/"

question_url  = "http://localhost:8011/api/v1/question/"
answer_url    = "http://localhost:8012/api/v1/answer/"

slide_url     = "http://localhost:8021/api/v1/slide/"

resource_url  = "http://localhost:8031/api/v1/resource/"
paper_url     = "http://localhost:8032/api/v1/paper/"

logic_url     = "http://localhost:8041/api/v1/logic/"
checker_url   = "http://localhost:3000/api/v1/checker/"

project_url   = "http://localhost:8051/api/v1/project/"
cron_url      = "http://localhost:8052/api/v1/cron/"

[default.databases.questions]
url = "postgres://base:base@localhost/base"
